<?php

use app\components\Utils;

/** @var array $item */

?>
<tr>
    <td class="cell bb_left middle"><?= $item['idx'] ?></td>
    <td class="cell"><?= $item['name'] ?></td>
    <td class="cell"><?= $item['note'] ?></td>
    <td class="cell middle"><?= $item['pricehigh'] ?></td>
    <td class="cell middle"><?= $item['quant'] ?></td>
    <td class="cell middle">шт.</td>
    <td class="cell middle bb_right"><?= $item['pricehighsum'] ?></td>
</tr>
