<?php

namespace app\controllers;

use app\components\BaseController;
use app\models\Objects;
use yii\filters\AccessControl;
use Yii;
use yii\filters\VerbFilter;

class ObjectController extends BaseController
{
    const PAGE_TITLE_INDEX = 'Список объектов';

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'update', 'create'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['ObjectView'],
                    ],
                    [
                        'actions' => ['update'],
                        'allow' => true,
                        'roles' => ['ObjectUpdate'],
                    ],
                    [
                        'actions' => ['create'],
                        'allow' => true,
                        'roles' => ['ObjectCreate'],
                    ],
                    [
                        'actions' => ['delete'],
                        'allow' => true,
                        'roles' => ['ObjectDelete'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function selectData()
    {
        parent::selectData(); // TODO: Change the autogenerated stub

        $this->source = Objects::find()
                            ->andWhere('objects.deldate is null')
                            ->joinWith('street')
                            ->joinWith('client')
                            ->joinWith('userManager');
    }


    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $this->selectData();

        return $this->render('index', [
            'source' => $this->source
        ]);
    }

    public function actionCreate()
    {
        $model = new Objects();
        $model->setScenario(Objects::SCENARIO_CREATE);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/object']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->setScenario(Objects::SCENARIO_UPDATE);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/object/view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Objects::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
