<?php

namespace app\components;

class AutoComplete extends BaseWidget
{
    public $id;
    public $caption;
    public $error;
    public $name;
    public $source;
    public $value;
    public $width;
    public $text;
    public $placeholder;
    public $readOnly = false;
    /** @var BaseActiveRecord $model */
    public $model;

    public $groupName;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (empty($this->id))
        {
            throw new \Exception("Нужно указать id автокомплита");
        }

        $this->name = empty($this->name) ? $this->id : $this->name;

        if ($this->model)
        {
            $this->name = $this->model->formName() .  (empty($this->groupName) ? '' : '[' . $this->groupName . ']') . '[' . $this->name . ']';
            $this->caption = isset($this->caption) ? $this->caption : $this->model->getAttributeLabel($this->id);
            $this->error = $this->model->getFirstError($this->id);
            $this->value = empty($this->value) ? $this->model->getAttribute($this->id) : $this->value;
        }
    }

    public function addClass(string $class) {
        $this->classes[] = $class;
        return $this;
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('autocomplete', [
            'widget' => $this
        ]);
    }

    public function getTextId()
    {
        return $this->id . '_text';
    }
}