<?php
namespace app\components;

class Breadcrumbs extends BaseWidget
{
    /** @var array */
    public $links;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (empty($this->links))
        {
            $this->links = [];
        }
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        return $this->render('breadcrumbs', [
            'links' => $this->links
        ]);
    }
}