<?php

namespace app\components;

use yii\db\Exception;

class Button extends BaseWidget
{
    public $id;
    public $value;
    public $href;
    public $target;
    public $type;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (empty($this->id))
        {
            throw new Exception("Необходимо указать ИД");
        }
    }

    public function run()
    {
        return $this->render('button', [
            'widget' => $this
        ]);
    }
}