<?php

namespace app\components;

class Form extends BaseWidget
{
    public $id;
    public $action = '';
    public $method = 'post';
    public $submitName = 'Сохранить';
    /** @var bool $button */
    public $button = true;
    /** @var BaseActiveRecord */
    public $model;
    public $enctype;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        ob_start();
    }

    public function run()
    {
        return $this->render('form', [
            'widget' => $this,
            'content' => ob_get_clean()
        ]);
    }

    public function createInputText($options)
    {
        return InputText::widget(array_merge($options, ['model' => $this->model]));
    }

    public function createInputPassword($options)
    {
        return InputPassword::widget(array_merge($options, ['model' => $this->model]));
    }

    public function createCheckBox($options)
    {
        return CheckBox::widget(array_merge($options, ['model' => $this->model]));
    }

    public function createAutoComplete($options)
    {
        return AutoComplete::widget(array_merge($options, ['model' => $this->model]));
    }

    public function createDateTimeInput($options)
    {
        return DateTimeInput::widget(array_merge($options, ['model' => $this->model]));
    }

    public function createTextArea($options)
    {
        return TextArea::widget(array_merge($options, ['model' => $this->model]));
    }

    public function createSelectInput($options)
    {
        return SelectInput::widget(array_merge($options, ['model' => $this->model]));
    }

    public function createDateInput($options)
    {
        return DateInput::widget(array_merge($options, ['model' => $this->model]));
    }

    public function createInputPrice($options)
    {
        return InputPrice::widget(array_merge($options, ['model' => $this->model]));
    }

    public function createInputFile($options)
    {
        return InputFile::widget(array_merge($options, ['model' => $this->model]));
    }
}