<?php

namespace app\components;

use yii\widgets\LinkPager as lp;

class LinkPager extends lp
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->view->registerCssFile('@web/css/components/linkpager.css');
    }

    public function run()
    {
        ob_start();
        parent::run();
        $html = ob_get_clean();
        return '<div class="linkpager">' . (empty($html) ? '<ul class="pagination"><li class="all">Загружены все записи</li></ul>' : $html)  . '</div>';
    }
}