<?php

namespace app\components;

class Table extends BaseWidget
{
    const FILTER_COND_LIKE = 'like';
    const FILTER_EQUAL = '=';
    const FILTER_ISNULL = 'is null';

    const BTN_INSERT    = 'insert';
    const BTN_EDIT    = 'update';
    const BTN_DELETE     = 'delete';


    public $id;

    public $options;

    /** @var BaseActiveRecord[] $data */
    public $data;
    /** @var array $columns */
    public $columns;
    /** @var array $classes */
    public $classes = [];

    public $enableFilters = false;

    public $rowAddClass;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!$this->columns)
        {
            $this->columns = [];
        }

        if (empty($this->id))
        {
            $this->id = 'table_' . rand(1, 100);
        }
    }

    public function addClass(string $class) {
        $this->classes[] = $class;
        return $this;
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('table', [
            'widget' => $this
        ]);
    }

    public function getPjaxId()
    {
        return 'pjax_' . $this->id;
    }

    public function getSubmitId()
    {
        return 'submit_' . $this->id;
    }
}