<?php

namespace app\components;

class TextArea extends BaseWidget
{
    public $id;
    public $caption;
    public $name;
    public $value;
    public $error;
    public $width;
    public $height;
    public $readOnly = false;
    /** @var BaseActiveRecord $model */
    public $model;
    /** @var string $groupName */
    public $groupName;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (empty($this->id))
        {
            throw new \Exception("Нужно указать id textarea");
        }

        $this->name = empty($this->name) ? $this->id : $this->name;

        if ($this->model)
        {
            $this->name = $this->model->formName() .  (empty($this->groupName) ? '' : '[' . $this->groupName . ']') . '[' . $this->name . ']';
            $this->caption = isset($this->caption) ? $this->caption : $this->model->getAttributeLabel($this->id);
            $this->error = $this->model->getFirstError($this->id);
            $this->value = empty($this->value) ? $this->model->getAttribute($this->id) : $this->value;
        }
    }

    public function run()
    {
        return $this->render('textarea', [
            'widget' => $this
        ]);
    }

}