<?php

namespace app\components;

class TopMenu extends BaseWidget
{
    public $options;
    /** @var array элементы меню */
    protected $tree;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!empty($this->options['tree'])) {
            $this->tree = $this->options['tree'];
        }
    }

    protected function getMenuHtml($tree)
    {
        $str = '';
        foreach ($tree as $item) {
            $visible = isset($item['visible']) ? $item['visible'] : true;
            if ($visible) {
                $str .= $this->itemToTemplate($item);
            }
        }
        return $str;
    }

    protected function itemToTemplate($item)
    {
        ob_start();
        include __DIR__ . '/views/topmenuitem.php';
        return ob_get_clean();
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('topmenu', [
            'html' => $this->getMenuHtml($this->tree)
        ]);
    }
}